CREATE DATABASE LIBRARY;
USE LIBRARY;

CREATE TABLE BOOK(IDBOOK INT NOTNULL, LANGUAGE INT NOT NULL, TITLE VARCHAR (200) NOTNULL, ISBN VARCHAR (17), NUMBER INT, QUANTITY INT NOT NULL, PRIMARY KEY(IDBOOK, LANGUAGE));

INSERT INTO BOOK(IDBOOK, "LANGUAGE", TITLE, ISBN, NUMBER, QUANTITY) VALUES (1,1,"Промышленное программирование", "978-985-6699-63-7", NULL, 5);
INSERT INTO BOOK(IDBOOK, "LANGUAGE", TITLE, ISBN, NUMBER, QUANTITY) VALUES (1,2,"Programming", "978-985-6699-63-7", NULL, 5);
